[package]
name = "barney_defense"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.96"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image", "ttf"]
